name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

permissions: write-all

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with: 
        node-version: '20.2'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Jekyll removal
      run: touch build/.nojekyll

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
